### ISSUE TITLE
If buildx is not configured, RAUDI fails

### ISSUE THREAD

**Issue by giper45** [cybersecsi/RAUDI#29]
**Describe the bug**

If you try to run RAUDI on a machine that has not configured buildx, the build fails. It is not relevant as we are focused on building the images, but it would be useful to add this information in README documentation in a clear way, as it could discourage people to contribute.   
 
**To Reproduce**

* Install docker without configuring buildx   
* run `python raudi.py --sinigle <nameimage>`  
* Look at the errors:   
<img width="489" alt="image" src="https://user-images.githubusercontent.com/18548727/150925589-6eca1f39-68ed-4190-8b39-1d97a277cb4d.png">

**Expected behavior**
Add in the README file that `buildx`  should be installed before contributing to the project.

**Comment by giper45** [comment]
Doc: 
https://docs.docker.com/buildx/working-with-buildx/

setup in `~/.docker/cli-plugins/docker-buildx` and `docker buildx install`

**Comment by thelicato** [comment]
Fixed in a3792ec2c0ca27925537dac9e7c321e8e3ec28a2, closing.
